import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# Function to read data points from a file
def read_points_from_file(filename):
    points = []
    with open(filename, 'r') as file:
        for line in file:
            if line.startswith('('):
                # Parse the line to extract the x, y, z coordinates
                point = tuple(map(float, line.strip('()\n').split(', ')))
                points.append(point)
    return np.array(points)

# Read the points from the text file generated by the C code
filename = 'data_points.txt'
line_points = read_points_from_file(filename)

# Plotting the points and the line in 3D
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

# Plot the data points read from the file
ax.plot(line_points[:, 0], line_points[:, 1], line_points[:, 2], color='b', label='Line through Points A,B,C')

# Labeling the axes
ax.set_xlabel('X axis')
ax.set_ylabel('Y axis')
ax.set_zlabel('Z axis')

# Set the aspect ratio of the plot to equal
ax.set_box_aspect([1, 1, 1])

# Set the limits of the plot
ax.set_xlim([-3, 8])
ax.set_ylim([-1, 4])
ax.set_zlim([-2, 6])

plt.title("Line passing through given points")
# Show the plot with legend
ax.legend()
plt.show()

